// js/materias.js

// ============================================
// MÓDULO DE MATÉRIAS
// ============================================

let materiasInicializado = false

// Inicializa o módulo quando a seção for acessada
function inicializarMaterias() {
  carregarMaterias()

  if (materiasInicializado) return
  materiasInicializado = true

  const btnAdicionar = document.getElementById('btn-adicionar-materia')
  const inputMateria = document.getElementById('input-materia')

  // Adicionar ao clicar no botão
  btnAdicionar.addEventListener('click', adicionarMateria)

  // Adicionar ao pressionar Enter no campo
  inputMateria.addEventListener('keydown', (e) => {
    if (e.key === 'Enter') adicionarMateria()
  })
}

// ============================================
// CARREGAR MATÉRIAS DO BANCO
// ============================================
async function carregarMaterias() {
  const lista = document.getElementById('lista-materias')
  const placeholder = document.getElementById('placeholder-materias')
  if (!lista || !placeholder) return

  // Mostra estado de carregando
  placeholder.textContent = '⏳ Buscando suas matérias...'
  placeholder.style.display = 'block'
  lista.replaceChildren(placeholder)

  const { data, error } = await db
    .from('materias')
    .select('id, nome, criado_em')
    .eq('user_id', window.usuarioAtual.id)
    .order('criado_em', { ascending: true })

  if (error) {
    placeholder.textContent = '❌ Erro ao carregar matérias.'
    return
  }

  if (!data || data.length === 0) {
    placeholder.textContent = '📚 Nenhuma matéria cadastrada ainda.'
    lista.replaceChildren(placeholder)
    return
  }

  // Esconde placeholder e renderiza os cards
  placeholder.style.display = 'none'
  lista.replaceChildren(placeholder)

  data.forEach(materia => {
    const card = criarCardMateria(materia)
    lista.appendChild(card)
  })
}

// ============================================
// CRIAR CARD DE MATÉRIA
// ============================================
function obterIconeMateria(nome) {
  const nomeLower = nome.toLowerCase()
  
  // Mapeamento de palavras-chave para ícones
  const icones = {
    'português': '📝',
    'portugues': '📝',
    'literatura': '📖',
    'matemática': '📐',
    'matematica': '📐',
    'álgebra': '∑',
    'algebra': '∑',
    'geometria': '📏',
    'física': '⚡',
    'fisica': '⚡',
    'química': '🧪',
    'quimica': '🧪',
    'biologia': '🧬',
    'história': '📜',
    'historia': '📜',
    'geografia': '🌍',
    'filosofia': '🤔',
    'sociologia': '👥',
    'direito': '⚖️',
    'constitucional': '⚖️',
    'penal': '🔒',
    'civil': '📋',
    'trabalhista': '💼',
    'tributário': '💰',
    'tributario': '💰',
    'administrativo': '🏛️',
    'informática': '💻',
    'informatica': '💻',
    'computação': '💻',
    'computacao': '💻',
    'programação': '⌨️',
    'programacao': '⌨️',
    'inglês': '🇬🇧',
    'ingles': '🇬🇧',
    'espanhol': '🇪🇸',
    'francês': '🇫🇷',
    'frances': '🇫🇷',
    'redação': '✍️',
    'redacao': '✍️',
    'interpretação': '📖',
    'interpretacao': '📖',
    'razão': '🧮',
    'razao': '🧮',
    'lógica': '🔍',
    'logica': '🔍',
    'estatística': '📊',
    'estatistica': '📊',
    'contabilidade': '📈',
    'economia': '💵',
    'administração': '📊',
    'administracao': '📊',
    'gestão': '📋',
    'gestao': '📋',
    'marketing': '📢',
    'vendas': '💼',
    'atualidades': '📰',
    'notícias': '📰',
    'noticias': '📰',
    'meio ambiente': '🌱',
    'sustentabilidade': '♻️',
    'saúde': '🏥',
    'saude': '🏥',
    'educação': '🎓',
    'educacao': '🎓',
    'pedagogia': '🎓',
    'psicologia': '🧠',
    'arte': '🎨',
    'música': '🎵',
    'musica': '🎵',
    'teatro': '🎭',
    'cinema': '🎬',
    'educação física': '⚽',
    'educacao fisica': '⚽',
    'esportes': '⚽',
    'conhecimentos específicos': '🎯',
    'legislação': '📜',
    'legislacao': '📜',
    'normas': '📋',
    'regulamentos': '📋',
    'técnico': '🔧',
    'tecnico': '🔧',
    'engenharia': '🏗️',
    'arquitetura': '🏛️',
    'design': '🎨',
    'segurança': '🛡️',
    'ti': '💻',
    'tecnologia': '💻',
    'dados': '📊',
    'banco de dados': '🗄️',
    'rede': '🌐',
    'redes': '🌐',
    'internet': '🌐',
    'web': '🌐',
    'mobile': '📱',
    'devops': '⚙️',
    'cloud': '☁️',
    'nuvem': '☁️',
    'ia': '🤖',
    'inteligência artificial': '🤖',
    'inteligencia artificial': '🤖',
    'machine learning': '🤖',
    'aprendizado': '📚',
    'pesquisa': '🔬',
    'ciência': '🔬',
    'ciencia': '🔬',
    'astronomia': '🌌',
    'meteorologia': '🌤️',
    'oceanografia': '🌊',
    'geologia': '🪨',
    'paleontologia': '🦕',
    'arqueologia': '🏺',
    'antropologia': '👤',
    'política': '🏛️',
    'politica': '🏛️',
    'relações internacionais': '🌐',
    'relacoes internacionais': '🌐',
    'diplomacia': '🤝',
    'comércio': '🛒',
    'comercio': '🛒',
    'finanças': '💹',
    'financas': '💹',
    'investimentos': '📈',
    'bolsa': '📈',
    'auditoria': '🔍',
    'controle': '✅',
    'fiscalização': '👁️',
    'fiscalizacao': '👁️',
    'planejamento': '📅',
    'orçamento': '💰',
    'orcamento': '💰',
    'recursos humanos': '👥',
    'rh': '👥',
    'concursos': '🎯',
    'provas': '📝',
    'questões': '❓',
    'questoes': '❓',
    'revisão': '🔄',
    'revisao': '🔄',
    'estudos': '📚',
    'aprender': '🧠',
    'ensino': '🎓',
    'curso': '📖',
    'aula': '👨‍🏫',
    'professor': '👨‍🏫',
    'aluno': '👨‍🎓',
    'estudante': '👨‍🎓',
    'vestibular': '🎯',
    'enem': '📝',
    'oab': '⚖️',
    'mpu': '⚖️',
    'tju': '⚖️',
    'stf': '⚖️',
    'stm': '⚖️',
    'tcu': '📊',
    'cg': '🔍',
    'pf': '👮',
    'prf': '🚔',
    'pm': '👮',
    'bm': '🚒',
    'pc': '🔍',
    'receita federal': '💰',
    'inss': '💼',
    'caixa': '🏦',
    'bacen': '💰',
    'cvm': '📈',
    'susep': '🛡️',
    'ans': '🏥',
    'anvisa': '💊',
    'mapa': '🌾',
    'embrapa': '🌱',
    'ibama': '🌳',
    'icmbio': '🦜',
    'funai': '👥',
    'incra': '📋',
    'ibge': '📊',
    'ipea': '📈',
    'fiocruz': '🔬',
    'butantan': '💉',
    'usp': '🎓',
    'unicamp': '🎓',
    'unesp': '🎓',
    'uf': '🎓',
    'if': '🎓',
    'cefet': '🎓',
    'senai': '🔧',
    'senac': '💼',
    'sesc': '🎭',
    'sesi': '🏭',
    'sebrae': '💼',
    'finep': '💰',
    'cnpq': '🔬',
    'capes': '🎓',
    'fapesp': '💰',
    'faperj': '💰',
    'fundect': '💰',
    'fundep': '💰',
    'consulplan': '📝',
    'cebraspe': '📝',
    'cespe': '📝',
    'fgv': '📝',
    'vunesp': '📝',
    'fcc': '📝',
    'ibfc': '📝',
    'quadrix': '📝',
    'institut': '📝',
    ' AOCP': '📝',
    'shdias': '📝',
    'la Salle': '📝',
    'uff': '📝',
    'uerj': '📝',
    'unirio': '📝',
    'ufrrj': '📝',
    'ufam': '📝',
    'ufpa': '📝',
    'ufba': '📝',
    'ufce': '📝',
    'ufpe': '📝',
    'ufla': '📝',
    'ufmg': '📝',
    'ufpr': '📝',
    'ufrgs': '📝',
    'ufsc': '📝',
    'ufsj': '📝',
    'ufv': '📝',
    'ufvjm': '📝',
    'unb': '📝',
    'unesp': '📝',
    'unifesp': '📝',
    'unitau': '📝',
    'puc': '📝',
    'mackenzie': '📝',
    'insper': '📝',
    'fgv': '📝',
    'ibmec': '📝',
    'esa': '🎓',
    'escola': '🎓',
    'academia': '🎓',
    'forças armadas': '🎖️',
    'forcas armadas': '🎖️',
    'exército': '🎖️',
    'exercito': '🎖️',
    'marinha': '⚓',
    'aeronáutica': '✈️',
    'aeronautica': '✈️',
    'fab': '✈️',
    'eb': '🎖️',
    'mb': '⚓',
    'guarda': '👮',
    'polícia': '👮',
    'policia': '👮',
    'bombeiro': '🚒',
    'bombeiros': '🚒',
    'defesa': '🛡️',
    'estratégia': '♟️',
    'estrategia': '♟️',
    'tática': '♟️',
    'tatica': '♟️',
    'operacional': '⚙️',
    'tático': '♟️',
    'tatico': '♟️',
    'emergencial': '🚨',
    'urgência': '🚨',
    'urgencia': '🚨',
    'crise': '🚨',
    'desastre': '🚨',
    'calamidade': '🚨',
    'socorro': '🆘',
    'resgate': '🚁',
    'salvamento': '🚁',
    'prevenção': '🛡️',
    'prevencao': '🛡️',
    'combate': '🥊',
    'incêndio': '🔥',
    'incendio': '🔥',
    'fogo': '🔥',
    'chama': '🔥',
    'explosão': '💥',
    'explosao': '💥',
    'acidente': '⚠️',
    'sinistro': '⚠️',
    'ocorrência': '📋',
    'ocorrencia': '📋',
    'incidente': '⚠️',
    'evento': '📅',
    'situação': '📋',
    'situacao': '📋',
    'caso': '📋',
    'processo': '📋',
    'procedimento': '📋',
    'protocolo': '📋',
    'rotina': '📋',
    'fluxo': '🔄',
    'método': '📋',
    'metodo': '📋',
    'técnica': '🔧',
    'tecnica': '🔧',
    'habilidade': '🎯',
    'competência': '🎯',
    'competencia': '🎯',
    'capacidade': '🎯',
    'aptidão': '🎯',
    'aptidao': '🎯',
    'treinamento': '🏋️',
    'treinamento': '🏋️',
    'capacitação': '🎓',
    'capacitacao': '🎓',
    'qualificação': '🎓',
    'qualificacao': '🎓',
    'certificação': '📜',
    'certificacao': '📜',
    'diploma': '📜',
    'certificado': '📜',
    'documento': '📄',
    'registro': '📝',
    'cadastro': '📝',
    'inscrição': '📝',
    'inscricao': '📝',
    'matrícula': '📝',
    'matricula': '📝',
    'frequência': '✅',
    'frequencia': '✅',
    'presença': '✅',
    'presenca': '✅',
    'ausência': '❌',
    'ausencia': '❌',
    'falta': '❌',
    'atraso': '⏰',
    'pontualidade': '⏰',
    'prazo': '⏰',
    'data': '📅',
    'hora': '⏰',
    'tempo': '⏱️',
    'duração': '⏱️',
    'duracao': '⏱️',
    'período': '📅',
    'periodo': '📅',
    'semestre': '📅',
    'trimestre': '📅',
    'bimestre': '📅',
    'ano': '📅',
    'mês': '📅',
    'mes': '📅',
    'semana': '📅',
    'dia': '📅',
    'turno': '🌅',
    'noite': '🌙',
    'tarde': '🌤️',
    'manhã': '🌅',
    'manha': '🌅',
    'madrugada': '🌌',
    'horário': '⏰',
    'horario': '⏰',
    'agenda': '📅',
    'calendário': '📅',
    'calendario': '📅',
    'cronograma': '📅',
    'planejamento': '📋',
    'organização': '📋',
    'organizacao': '📋',
    'estrutura': '🏗️',
    'hierarquia': '📊',
    'departamento': '🏢',
    'setor': '🏢',
    'divisão': '📊',
    'divisao': '📊',
    'seção': '📊',
    'secao': '📊',
    'grupo': '👥',
    'equipe': '👥',
    'time': '👥',
    'staff': '👥',
    'pessoal': '👥',
    'colaborador': '👤',
    'funcionário': '👤',
    'funcionario': '👤',
    'servidor': '👤',
    'empregado': '👤',
    'chefe': '👔',
    'gerente': '👔',
    'diretor': '👔',
    'presidente': '👔',
    'coordenador': '👔',
    'supervisor': '👔',
    'líder': '⭐',
    'lider': '⭐',
    'gestor': '👔',
    'executivo': '👔',
    'analista': '📊',
    'técnico': '🔧',
    'tecnico': '🔧',
    'assistente': '📋',
    'auxiliar': '📋',
    'estagiário': '🎓',
    'estagiario': '🎓',
    'trainee': '🎓',
    'junior': '🌱',
    'pleno': '🌿',
    'senior': '🌳',
    'especialista': '⭐',
    'expert': '⭐',
    'mestre': '🎓',
    'doutor': '🎓',
    'phd': '🎓',
    'pesquisador': '🔬',
    'cientista': '🔬',
    'inventor': '💡',
    'criador': '🎨',
    'autor': '✍️',
    'escritor': '✍️',
    'poeta': '✍️',
    'jornalista': '📰',
    'repórter': '📰',
    'reporter': '📰',
    'editor': '📝',
    'revisor': '🔍',
    'tradutor': '🌐',
    'intérprete': '🗣️',
    'interprete': '🗣️',
    'narrador': '📖',
    'locutor': '🎙️',
    'apresentador': '🎤',
    'comentarista': '🎙️',
    'crítico': '⭐',
    'critico': '⭐',
    'avaliador': '⭐',
    'juiz': '⚖️',
    'desembargador': '⚖️',
    'ministro': '⚖️',
    'promotor': '⚖️',
    'procurador': '⚖️',
    'advogado': '⚖️',
    'defensor': '🛡️',
    'delegado': '👮',
    'escrivão': '📝',
    'escrivao': '📝',
    'investigador': '🔍',
    'detetive': '🔍',
    'perito': '🔬',
    'papiloscopista': '👆',
    'criminalístico': '🔬',
    'criminalistico': '🔬',
    'forense': '🔬',
    'médico': '🩺',
    'medico': '🩺',
    'enfermeiro': '💉',
    'farmacêutico': '💊',
    'farmaceutico': '💊',
    'nutricionista': '🍎',
    'psicólogo': '🧠',
    'psicologo': '🧠',
    'psiquiatra': '🧠',
    'terapeuta': '💆',
    'fisioterapeuta': '🏃',
    'fonoaudiólogo': '🗣️',
    'fonoaudiologo': '🗣️',
    'odontólogo': '🦷',
    'odontologo': '🦷',
    'dentista': '🦷',
    'veterinário': '🐾',
    'veterinario': '🐾',
    'zootecnista': '🐾',
    'agrônomo': '🌾',
    'agronomo': '🌾',
    'engenheiro': '🏗️',
    'arquiteto': '🏛️',
    'urbanista': '🏙️',
    'designer': '🎨',
    'artista': '🎨',
    'músico': '🎵',
    'musico': '🎵',
    'cantor': '🎤',
    'ator': '🎭',
    'atriz': '🎭',
    'dançarino': '💃',
    'dancarino': '💃',
    'coreógrafo': '💃',
    'coreografo': '💃',
    'fotógrafo': '📷',
    'fotografo': '📷',
    'cineasta': '🎬',
    'diretor': '🎬',
    'produtor': '🎬',
    'roteirista': '✍️',
    'animador': '🎨',
    'ilustrador': '🎨',
    'cartunista': '🎨',
    'quadrinista': '🎨',
    'game designer': '🎮',
    'desenvolvedor': '💻',
    'programador': '💻',
    'coder': '💻',
    'hacker': '💻',
    'security': '🔒',
    'segurança': '🔒',
    'network': '🌐',
    'database': '🗄️',
    'dba': '🗄️',
    'sysadmin': '⚙️',
    'devops': '⚙️',
    'sre': '⚙️',
    'qa': '✅',
    'tester': '✅',
    'scrum': '🔄',
    'agile': '🔄',
    'kanban': '📋',
    'product owner': '🎯',
    'po': '🎯',
    'sm': '🔄',
    'coach': '🎯',
    'mentor': '🎯',
    'consultor': '💼',
    'assessor': '💼',
    'analista': '📊',
    'estrategista': '♟️',
    'planejador': '📋',
    'organizador': '📋',
    'facilitador': '🤝',
    'mediador': '🤝',
    'negociador': '🤝',
    'comercial': '💼',
    'vendedor': '💼',
    'representante': '💼',
    'corretor': '💼',
    'correspondente': '💼',
    'agente': '💼',
    'distribuidor': '🚚',
    'logística': '🚚',
    'logistica': '🚚',
    'transporte': '🚚',
    'entrega': '📦',
    'shipping': '📦',
    'frete': '📦',
    'cargo': '📦',
    'importação': '🚢',
    'importacao': '🚢',
    'exportação': '✈️',
    'exportacao': '✈️',
    'comércio exterior': '🌐',
    'comercio exterior': '🌐',
    'exterior': '🌐',
    'internacional': '🌐',
    'global': '🌐',
    'mundial': '🌐',
    'universal': '🌐',
    'geral': '📋',
    'comum': '📋',
    'básico': '📚',
    'basico': '📚',
    'elementar': '📚',
    'fundamental': '📚',
    'essencial': '⭐',
    'principal': '⭐',
    'primário': '⭐',
    'primario': '⭐',
    'secundário': '📊',
    'secundario': '📊',
    'terciário': '🏢',
    'terciario': '🏢',
    'quaternário': '💻',
    'quaternario': '💻',
    'avançado': '🚀',
    'avancado': '🚀',
    'intermediário': '📈',
    'intermediario': '📈',
    'profissional': '💼',
    'técnico': '🔧',
    'tecnológico': '💻',
    'tecnologico': '💻',
    'científico': '🔬',
    'cientifico': '🔬',
    'acadêmico': '🎓',
    'academico': '🎓',
    'escolar': '🏫',
    'universitário': '🎓',
    'universitario': '🎓',
    'faculdade': '🎓',
    'graduação': '🎓',
    'graduacao': '🎓',
    'pós': '🎓',
    'pos': '🎓',
    'mestrado': '🎓',
    'doutorado': '🎓',
    'specialization': '🎓',
    'mba': '🎓',
    'executive': '🎓',
    'business': '💼',
    'management': '👔',
    'administration': '🏢',
    'finance': '💰',
    'accounting': '📊',
    'marketing': '📢',
    'sales': '💼',
    'hr': '👥',
    'operations': '⚙️',
    'production': '🏭',
    'quality': '✅',
    'supply': '📦',
    'chain': '🔗',
    'procurement': '💼',
    'purchasing': '💼',
    'sourcing': '💼',
    'vendor': '💼',
    'supplier': '💼',
    'client': '🤝',
    'customer': '🤝',
    'consumer': '🛒',
    'user': '👤',
    'end user': '👤',
    'stakeholder': '👥',
    'partner': '🤝',
    'ally': '🤝',
    'collaborator': '🤝',
    'contributor': '🤝',
    'volunteer': '❤️',
    'intern': '🎓',
    'apprentice': '🎓',
    'trainee': '🎓',
    'newbie': '🌱',
    'beginner': '🌱',
    'novice': '🌱',
    'starter': '🌱',
    'rookie': '🌱',
    'freshman': '🌱',
    'sophomore': '🌿',
    'junior': '🌿',
    'mid': '🌳',
    'middle': '🌳',
    'regular': '🌳',
    'standard': '🌳',
    'normal': '🌳',
    'typical': '🌳',
    'usual': '🌳',
    'common': '🌳',
    'ordinary': '🌳',
    'average': '🌳',
    'medium': '🌳',
    'moderate': '🌳',
    'balanced': '⚖️',
    'stable': '✅',
    'steady': '✅',
    'consistent': '✅',
    'reliable': '✅',
    'dependable': '✅',
    'trustworthy': '✅',
    'honest': '✅',
    'ethical': '✅',
    'moral': '✅',
    'virtuous': '✅',
    'good': '✅',
    'great': '⭐',
    'excellent': '⭐',
    'outstanding': '⭐',
    'exceptional': '⭐',
    'remarkable': '⭐',
    'extraordinary': '⭐',
    'amazing': '⭐',
    'awesome': '⭐',
    'fantastic': '⭐',
    'wonderful': '⭐',
    'marvelous': '⭐',
    'superb': '⭐',
    'splendid': '⭐',
    'magnificent': '⭐',
    'glorious': '⭐',
    'brilliant': '⭐',
    'genius': '🧠',
    'smart': '🧠',
    'intelligent': '🧠',
    'clever': '🧠',
    'wise': '🧠',
    'knowledgeable': '🧠',
    'educated': '🎓',
    'learned': '🎓',
    'scholarly': '🎓',
    'academic': '🎓',
    'intellectual': '🧠',
    'cerebral': '🧠',
    'thoughtful': '🤔',
    'reflective': '🤔',
    'contemplative': '🤔',
    'philosophical': '🤔',
    'theoretical': '🤔',
    'abstract': '🤔',
    'conceptual': '🤔',
    'ideological': '🤔',
    'doctrinal': '🤔',
    'principled': '🤔',
    'systematic': '📋',
    'methodical': '📋',
    'organized': '📋',
    'structured': '📋',
    'ordered': '📋',
    'arranged': '📋',
    'planned': '📋',
    'scheduled': '📅',
    'timed': '⏰',
    'paced': '⏱️',
    'measured': '📏',
    'calculated': '🧮',
    'computed': '🧮',
    'estimated': '📊',
    'projected': '📊',
    'forecasted': '📊',
    'predicted': '🔮',
    'anticipated': '🔮',
    'expected': '🔮',
    'anticipated': '🔮',
    'hoped': '🤞',
    'wished': '🌟',
    'desired': '🌟',
    'wanted': '🌟',
    'needed': '🌟',
    'required': '🌟',
    'necessary': '🌟',
    'essential': '🌟',
    'vital': '🌟',
    'critical': '🌟',
    'crucial': '🌟',
    'key': '🔑',
    'main': '⭐',
    'primary': '⭐',
    'principal': '⭐',
    'chief': '⭐',
    'head': '⭐',
    'top': '⭐',
    'leading': '⭐',
    'foremost': '⭐',
    'premier': '⭐',
    'prime': '⭐',
    'first': '1️⃣',
    'initial': '1️⃣',
    'original': '1️⃣',
    'earliest': '1️⃣',
    'opening': '1️⃣',
    'introductory': '1️⃣',
    'preliminary': '1️⃣',
    'preparatory': '1️⃣',
    'foundational': '1️⃣',
    'basic': '1️⃣',
    'fundamental': '1️⃣',
    'elementary': '1️⃣',
    'intro': '1️⃣',
    'beginning': '1️⃣',
    'start': '1️⃣',
    'commencement': '1️⃣',
    'onset': '1️⃣',
    'outset': '1️⃣',
    'kickoff': '1️⃣',
    'launch': '🚀',
    'initiation': '🚀',
    'inauguration': '🚀',
    'debut': '🚀',
    'premiere': '🚀',
    'unveiling': '🚀',
    'reveal': '🚀',
    'disclosure': '🚀',
    'announcement': '📢',
    'declaration': '📢',
    'proclamation': '📢',
    'statement': '📢',
    'release': '📢',
    'bulletin': '📢',
    'notice': '📢',
    'alert': '🚨',
    'warning': '⚠️',
    'caution': '⚠️',
    'advisory': '⚠️',
    'notification': '🔔',
    'reminder': '🔔',
    'memo': '📝',
    'message': '💬',
    'communication': '💬',
    'correspondence': '💬',
    'exchange': '🔄',
    'dialogue': '💬',
    'conversation': '💬',
    'discussion': '💬',
    'debate': '💬',
    'argument': '💬',
    'dispute': '⚔️',
    'conflict': '⚔️',
    'disagreement': '⚔️',
    'difference': '⚔️',
    'opposition': '⚔️',
    'resistance': '🛡️',
    'defense': '🛡️',
    'protection': '🛡️',
    'security': '🛡️',
    'safety': '🛡️',
    'safeguard': '🛡️',
    'shield': '🛡️',
    'guard': '🛡️',
    'watch': '👁️',
    'surveillance': '👁️',
    'monitoring': '👁️',
    'observation': '👁️',
    'inspection': '👁️',
    'examination': '👁️',
    'review': '👁️',
    'audit': '👁️',
    'check': '✅',
    'verification': '✅',
    'validation': '✅',
    'confirmation': '✅',
    'approval': '✅',
    'authorization': '✅',
    'permission': '✅',
    'consent': '✅',
    'agreement': '✅',
    'acceptance': '✅',
    'acknowledgment': '✅',
    'recognition': '✅',
    'appreciation': '❤️',
    'gratitude': '❤️',
    'thanks': '❤️',
    'praise': '❤️',
    'commendation': '❤️',
    'acclaim': '❤️',
    'applause': '👏',
    'ovation': '👏',
    'celebration': '🎉',
    'festivity': '🎉',
    'party': '🎉',
    'gathering': '👥',
    'meeting': '👥',
    'assembly': '👥',
    'conference': '👥',
    'convention': '👥',
    'symposium': '👥',
    'seminar': '👥',
    'workshop': '👥',
    'training': '👥',
    'session': '👥',
    'class': '👥',
    'lesson': '👥',
    'lecture': '👥',
    'presentation': '👥',
    'demonstration': '👥',
    'exhibition': '👥',
    'display': '👥',
    'show': '👥',
    'performance': '👥',
    'act': '🎭',
    'play': '🎭',
    'drama': '🎭',
    'comedy': '🎭',
    'tragedy': '🎭',
    'musical': '🎵',
    'opera': '🎵',
    'concert': '🎵',
    'recital': '🎵',
    'song': '🎵',
    'melody': '🎵',
    'tune': '🎵',
    'rhythm': '🎵',
    'beat': '🎵',
    'tempo': '🎵',
    'harmony': '🎵',
    'chord': '🎵',
    'note': '🎵',
    'scale': '🎵',
    'key': '🎵',
    'mode': '🎵',
    'style': '🎵',
    'genre': '🎵',
    'type': '📋',
    'category': '📋',
    'classification': '📋',
    'grouping': '📋',
    'sorting': '📋',
    'ranking': '📊',
    'rating': '📊',
    'scoring': '📊',
    'grading': '📊',
    'evaluation': '📊',
    'assessment': '📊',
    'appraisal': '📊',
    'judgment': '⚖️',
    'opinion': '💭',
    'view': '💭',
    'perspective': '💭',
    'standpoint': '💭',
    'position': '💭',
    'stance': '💭',
    'attitude': '💭',
    'approach': '💭',
    'angle': '💭',
    'slant': '💭',
    'bias': '💭',
    'prejudice': '💭',
    'predilection': '💭',
    'preference': '💭',
    'inclination': '💭',
    'tendency': '💭',
    'propensity': '💭',
    'leaning': '💭',
    'bent': '💭',
    'knack': '💭',
    'talent': '⭐',
    'gift': '⭐',
    'ability': '⭐',
    'capability': '⭐',
    'capacity': '⭐',
    'potential': '⭐',
    'promise': '⭐',
    'prospect': '⭐',
    'possibility': '⭐',
    'opportunity': '⭐',
    'chance': '⭐',
    'luck': '🍀',
    'fortune': '🍀',
    'destiny': '🌟',
    'fate': '🌟',
    'doom': '🌟',
    'lot': '🌟',
    'portion': '🌟',
    'share': '🌟',
    'part': '🌟',
    'piece': '🌟',
    'segment': '🌟',
    'section': '🌟',
    'division': '🌟',
    'department': '🌟',
    'branch': '🌟',
    'wing': '🌟',
    'arm': '🌟',
    'unit': '🌟',
    'team': '🌟',
    'crew': '🌟',
    'squad': '🌟',
    'gang': '🌟',
    'band': '🌟',
    'group': '🌟',
    'cluster': '🌟',
    'bunch': '🌟',
    'batch': '🌟',
    'set': '🌟',
    'series': '🌟',
    'sequence': '🌟',
    'succession': '🌟',
    'chain': '🌟',
    'string': '🌟',
    'line': '🌟',
    'row': '🌟',
    'tier': '🌟',
    'level': '🌟',
    'grade': '🌟',
    'rank': '🌟',
    'status': '🌟',
    'standing': '🌟',
    'position': '🌟',
    'place': '🌟',
    'spot': '🌟',
    'location': '🌟',
    'site': '🌟',
    'venue': '🌟',
    'ground': '🌟',
    'field': '🌟',
    'area': '🌟',
    'zone': '🌟',
    'region': '🌟',
    'district': '🌟',
    'sector': '🌟',
    'quarter': '🌟',
    'neighborhood': '🌟',
    'community': '🌟',
    'locality': '🌟',
    'vicinity': '🌟',
    'proximity': '🌟',
    'nearness': '🌟',
    'closeness': '🌟',
    'intimacy': '🌟',
    'familiarity': '🌟',
    'acquaintance': '🌟',
    'knowledge': '🌟',
    'awareness': '🌟',
    'consciousness': '🌟',
    'realization': '🌟',
    'recognition': '🌟',
    'understanding': '🌟',
    'comprehension': '🌟',
    'grasp': '🌟',
    'grip': '🌟',
    'hold': '🌟',
    'control': '🌟',
    'command': '🌟',
    'mastery': '🌟',
    'skill': '🌟',
    'expertise': '🌟',
    'proficiency': '🌟',
    'competence': '🌟',
    'adeptness': '🌟',
    'dexterity': '🌟',
    'adroitness': '🌟',
    'finesse': '🌟',
    'artistry': '🌟',
    'craftsmanship': '🌟',
    'workmanship': '🌟',
    'quality': '🌟',
    'excellence': '🌟',
    'superiority': '🌟',
    'distinction': '🌟',
    'merit': '🌟',
    'worth': '🌟',
    'value': '🌟',
    'importance': '🌟',
    'significance': '🌟',
    'consequence': '🌟',
    'moment': '🌟',
    'weight': '🌟',
    'impact': '🌟',
    'effect': '🌟',
    'influence': '🌟',
    'power': '🌟',
    'force': '🌟',
    'strength': '🌟',
    'might': '🌟',
    'energy': '🌟',
    'vigor': '🌟',
    'vitality': '🌟',
    'spirit': '🌟',
    'life': '🌟',
    'animation': '🌟',
    'liveliness': '🌟',
    'vivacity': '🌟',
    'enthusiasm': '🌟',
    'passion': '🌟',
    'zeal': '🌟',
    'fervor': '🌟',
    'ardor': '🌟',
    'intensity': '🌟',
    'earnestness': '🌟',
    'sincerity': '🌟',
    'honesty': '🌟',
    'truthfulness': '🌟',
    'veracity': '🌟',
    'accuracy': '🌟',
    'precision': '🌟',
    'exactness': '🌟',
    'correctness': '🌟',
    'rightness': '🌟',
    'propriety': '🌟',
    'appropriateness': '🌟',
    'suitability': '🌟',
    'fitness': '🌟',
    'aptitude': '🌟',
    'qualification': '🌟',
    'credential': '🌟',
    'certification': '🌟',
    'license': '🌟',
    'permit': '🌟',
    'warrant': '🌟',
    'authorization': '🌟',
    'sanction': '🌟',
    'approval': '🌟',
    'endorsement': '🌟',
    'support': '🌟',
    'backing': '🌟',
    'assistance': '🌟',
    'aid': '🌟',
    'help': '🌟',
    'service': '🌟',
    'favor': '🌟',
    'kindness': '🌟',
    'generosity': '🌟',
    'charity': '🌟',
    'benevolence': '🌟',
    'goodwill': '🌟',
    'friendliness': '🌟',
    'warmth': '🌟',
    'affection': '🌟',
    'love': '🌟',
    'devotion': '🌟',
    'loyalty': '🌟',
    'faithfulness': '🌟',
    'allegiance': '🌟',
    'dedication': '🌟',
    'commitment': '🌟',
    'obligation': '🌟',
    'responsibility': '🌟',
    'duty': '🌟',
    'task': '🌟',
    'job': '🌟',
    'work': '🌟',
    'labor': '🌟',
    'effort': '🌟',
    'endeavor': '🌟',
    'attempt': '🌟',
    'try': '🌟',
    'trial': '🌟',
    'test': '🌟',
    'experiment': '🌟',
    'exercise': '🌟',
    'practice': '🌟',
    'drill': '🌟',
    'rehearsal': '🌟',
    'preparation': '🌟',
    'training': '🌟',
    'education': '🌟',
    'instruction': '🌟',
    'teaching': '🌟',
    'learning': '🌟',
    'study': '🌟',
    'research': '🌟',
    'investigation': '🌟',
    'exploration': '🌟',
    'discovery': '🌟',
    'finding': '🌟',
    'result': '🌟',
    'outcome': '🌟',
    'conclusion': '🌟',
    'resolution': '🌟',
    'solution': '🌟',
    'answer': '🌟',
    'response': '🌟',
    'reply': '🌟',
    'reaction': '🌟',
    'feedback': '🌟',
    'input': '🌟',
    'output': '🌟',
    'product': '🌟',
    'output': '🌟',
    'deliverable': '🌟',
    'artifact': '🌟',
    'document': '🌟',
    'report': '🌟',
    'record': '🌟',
    'file': '🌟',
    'data': '🌟',
    'information': '🌟',
    'knowledge': '🌟',
    'wisdom': '🌟',
    'insight': '🌟',
    'understanding': '🌟',
    'comprehension': '🌟',
    'awareness': '🌟',
    'consciousness': '🌟',
    'perception': '🌟',
    'cognition': '🌟',
    'thinking': '🌟',
    'reasoning': '🌟',
    'logic': '🌟',
    'analysis': '🌟',
    'synthesis': '🌟',
    'evaluation': '🌟',
    'judgment': '🌟',
    'decision': '🌟',
    'choice': '🌟',
    'selection': '🌟',
    'option': '🌟',
    'alternative': '🌟',
    'possibility': '🌟',
    'probability': '🌟',
    'likelihood': '🌟',
    'chance': '🌟',
    'risk': '🌟',
    'uncertainty': '🌟',
    'doubt': '🌟',
    'question': '🌟',
    'query': '🌟',
    'inquiry': '🌟',
    'investigation': '🌟',
    'examination': '🌟',
    'inspection': '🌟',
    'survey': '🌟',
    'poll': '🌟',
    'census': '🌟',
    'count': '🌟',
    'tally': '🌟',
    'score': '🌟',
    'total': '🌟',
    'sum': '🌟',
    'amount': '🌟',
    'quantity': '🌟',
    'number': '🌟',
    'figure': '🌟',
    'statistic': '🌟',
    'percentage': '🌟',
    'ratio': '🌟',
    'rate': '🌟',
    'proportion': '🌟',
    'fraction': '🌟',
    'part': '🌟',
    'portion': '🌟',
    'share': '🌟',
    'slice': '🌟',
    'piece': '🌟',
    'bit': '🌟',
    'fragment': '🌟',
    'segment': '🌟',
    'section': '🌟',
    'division': '🌟',
    'component': '🌟',
    'element': '🌟',
    'factor': '🌟',
    'aspect': '🌟',
    'feature': '🌟',
    'characteristic': '🌟',
    'trait': '🌟',
    'quality': '🌟',
    'attribute': '🌟',
    'property': '🌟',
    'nature': '🌟',
    'essence': '🌟',
    'substance': '🌟',
    'material': '🌟',
    'matter': '🌟',
    'stuff': '🌟',
    'thing': '🌟',
    'object': '🌟',
    'item': '🌟',
    'article': '🌟',
    'piece': '🌟',
    'unit': '🌟',
    'individual': '🌟',
    'person': '🌟',
    'human': '🌟',
    'being': '🌟',
    'soul': '🌟',
    'spirit': '🌟',
    'mind': '🌟',
    'body': '🌟',
    'flesh': '🌟',
    'blood': '🌟',
    'bone': '🌟',
    'muscle': '🌟',
    'tissue': '🌟',
    'cell': '🌟',
    'organ': '🌟',
    'system': '🌟',
    'structure': '🌟',
    'framework': '🌟',
    'skeleton': '🌟',
    'shell': '🌟',
    'housing': '🌟',
    'container': '🌟',
    'vessel': '🌟',
    'receptacle': '🌟',
    'holder': '🌟',
    'carrier': '🌟',
    'transport': '🌟',
    'vehicle': '🌟',
    'conveyance': '🌟',
    'craft': '🌟',
    'ship': '🌟',
    'boat': '🌟',
    'plane': '🌟',
    'aircraft': '🌟',
    'helicopter': '🌟',
    'rocket': '🌟',
    'missile': '🌟',
    'satellite': '🌟',
    'probe': '🌟',
    'rover': '🌟',
    'lander': '🌟',
    'station': '🌟',
    'base': '🌟',
    'camp': '🌟',
    'outpost': '🌟',
    'fort': '🌟',
    'castle': '🌟',
    'palace': '🌟',
    'mansion': '🌟',
    'house': '🌟',
    'home': '🌟',
    'residence': '🌟',
    'dwelling': '🌟',
    'abode': '🌟',
    'habitat': '🌟',
    'environment': '🌟',
    'surroundings': '🌟',
    'setting': '🌟',
    'context': '🌟',
    'background': '🌟',
    'scene': '🌟',
    'scenery': '🌟',
    'landscape': '🌟',
    'vista': '🌟',
    'view': '🌟',
    'sight': '🌟',
    'spectacle': '🌟',
    'display': '🌟',
    'show': '🌟',
    'exhibition': '🌟',
    'demonstration': '🌟',
    'presentation': '🌟',
    'performance': '🌟',
    'act': '🌟',
    'play': '🌟',
    'drama': '🌟',
    'comedy': '🌟',
    'tragedy': '🌟',
    'farce': '🌟',
    'skit': '🌟',
    'sketch': '🌟',
    'routine': '🌟',
    'number': '🌟',
    'turn': '🌟',
    'feat': '🌟',
    'stunt': '🌟',
    'trick': '🌟',
    'illusion': '🌟',
    'magic': '🌟',
    'spell': '🌟',
    'charm': '🌟',
    'hex': '🌟',
    'curse': '🌟',
    'jinx': '🌟',
    'hoodoo': '🌟',
    'voodoo': '🌟',
    'sorcery': '🌟',
    'witchcraft': '🌟',
    'wizardry': '🌟',
    'enchantment': '🌟',
    'bewitchment': '🌟',
    'conjuration': '🌟',
    'invocation': '🌟',
    'evocation': '🌟',
    'summoning': '🌟',
    'calling': '🌟',
    'beckoning': '🌟',
    'gesture': '🌟',
    'signal': '🌟',
    'sign': '🌟',
    'symbol': '🌟',
    'token': '🌟',
    'emblem': '🌟',
    'badge': '🌟',
    'mark': '🌟',
    'stamp': '🌟',
    'seal': '🌟',
    'label': '🌟',
    'tag': '🌟',
    'ticket': '🌟',
    'pass': '🌟',
    'permit': '🌟',
    'license': '🌟',
    'certificate': '🌟',
    'diploma': '🌟',
    'degree': '🌟',
    'title': '🌟',
    'rank': '🌟',
    'grade': '🌟',
    'level': '🌟',
    'class': '🌟',
    'category': '🌟',
    'type': '🌟',
    'kind': '🌟',
    'sort': '🌟',
    'variety': '🌟',
    'species': '🌟',
    'breed': '🌟',
    'strain': '🌟',
    'stock': '🌟',
    'line': '🌟',
    'family': '🌟',
    'clan': '🌟',
    'tribe': '🌟',
    'race': '🌟',
    'people': '🌟',
    'nation': '🌟',
    'country': '🌟',
    'state': '🌟',
    'land': '🌟',
    'realm': '🌟',
    'domain': '🌟',
    'territory': '🌟',
    'region': '🌟',
    'zone': '🌟',
    'area': '🌟',
    'district': '🌟',
    'sector': '🌟',
    'quarter': '🌟',
    'neighborhood': '🌟',
    'locality': '🌟',
    'vicinity': '🌟',
    'proximity': '🌟',
    'nearness': '🌟',
    'closeness': '🌟',
    'distance': '🌟',
    'remoteness': '🌟',
    'farness': '🌟',
    'space': '🌟',
    'gap': '🌟',
    'interval': '🌟',
    'pause': '🌟',
    'break': '🌟',
    'rest': '🌟',
    'recess': '🌟',
    'hiatus': '🌟',
    'lacuna': '🌟',
    'void': '🌟',
    'vacuum': '🌟',
    'emptiness': '🌟',
    'nothingness': '🌟',
    'null': '🌟',
    'zero': '0️⃣',
    'nil': '0️⃣',
    'naught': '0️⃣',
    'cipher': '0️⃣',
    'nought': '0️⃣',
    ' zilch': '0️⃣',
    'zip': '0️⃣',
    ' nada': '0️⃣',
    'none': '0️⃣',
    'no one': '0️⃣',
    'nobody': '0️⃣',
    'nothing': '0️⃣',
    'nowhere': '0️⃣',
    'never': '0️⃣',
    'neither': '0️⃣',
    'nor': '0️⃣',
    'not': '0️⃣',
    'no': '0️⃣',
    'negative': '0️⃣',
    'denial': '0️⃣',
    'refusal': '0️⃣',
    'rejection': '0️⃣',
    'dismissal': '0️⃣',
    'repudiation': '0️⃣',
    'renunciation': '0️⃣',
    'abdication': '0️⃣',
    'resignation': '0️⃣',
    'surrender': '0️⃣',
    'submission': '0️⃣',
    'yielding': '0️⃣',
    'capitulation': '0️⃣',
    'concession': '0️⃣',
    'compromise': '0️⃣',
    'settlement': '0️⃣',
    'agreement': '0️⃣',
    'accord': '0️⃣',
    'pact': '0️⃣',
    'treaty': '0️⃣',
    'contract': '0️⃣',
    'deal': '0️⃣',
    'bargain': '0️⃣',
    'arrangement': '0️⃣',
    'understanding': '0️⃣',
    'compact': '0️⃣',
    'covenant': '0️⃣',
    'pledge': '0️⃣',
    'vow': '0️⃣',
    'oath': '0️⃣',
    'promise': '0️⃣',
    'word': '0️⃣',
    'guarantee': '0️⃣',
    'assurance': '0️⃣',
    'warranty': '0️⃣',
    'security': '0️⃣',
    'safeguard': '0️⃣',
    'protection': '0️⃣',
    'defense': '0️⃣',
    'shield': '0️⃣',
    'guard': '0️⃣',
    'screen': '0️⃣',
    'barrier': '0️⃣',
    'wall': '0️⃣',
    'fence': '0️⃣',
    'hedge': '0️⃣',
    'boundary': '0️⃣',
    'border': '0️⃣',
    'frontier': '0️⃣',
    'limit': '0️⃣',
    'bound': '0️⃣',
    'term': '0️⃣',
    'condition': '0️⃣',
    'requirement': '0️⃣',
    'specification': '0️⃣',
    'criterion': '0️⃣',
    'standard': '0️⃣',
    'norm': '0️⃣',
    'rule': '0️⃣',
    'regulation': '0️⃣',
    'law': '0️⃣',
    'statute': '0️⃣',
    'ordinance': '0️⃣',
    'decree': '0️⃣',
    'edict': '0️⃣',
    'mandate': '0️⃣',
    'order': '0️⃣',
    'directive': '0️⃣',
    'instruction': '0️⃣',
    'command': '0️⃣',
    'injunction': '0️⃣',
    'behest': '0️⃣',
    'bid': '0️⃣',
    'call': '0️⃣',
    'request': '0️⃣',
    'appeal': '0️⃣',
    'petition': '0️⃣',
    'plea': '0️⃣',
    'application': '0️⃣',
    'solicitation': '0️⃣',
    'entreaty': '0️⃣',
    'supplication': '0️⃣',
    'invocation': '0️⃣',
    'prayer': '0️⃣',
    'worship': '0️⃣',
    'devotion': '0️⃣',
    'reverence': '0️⃣',
    'veneration': '0️⃣',
    'adoration': '0️⃣',
    'homage': '0️⃣',
    'tribute': '0️⃣',
    'offering': '0️⃣',
    'gift': '0️⃣',
    'present': '0️⃣',
    'donation': '0️⃣',
    'contribution': '0️⃣',
    'grant': '0️⃣',
    'award': '0️⃣',
    'prize': '0️⃣',
    'reward': '0️⃣',
    'bonus': '0️⃣',
    'premium': '0️⃣',
    ' bounty': '0️⃣',
    'jackpot': '0️⃣',
    'windfall': '0️⃣',
    'godsend': '0️⃣',
    'blessing': '0️⃣',
    'boon': '0️⃣',
    'benefit': '0️⃣',
    'advantage': '0️⃣',
    'profit': '0️⃣',
    'gain': '0️⃣',
    'return': '0️⃣',
    'yield': '0️⃣',
    'income': '0️⃣',
    'revenue': '0️⃣',
    'earnings': '0️⃣',
    'proceeds': '0️⃣',
    'receipts': '0️⃣',
    'takings': '0️⃣',
    'collection': '0️⃣',
    'haul': '0️⃣',
    'catch': '0️⃣',
    'take': '0️⃣',
    'score': '0️⃣',
    'kill': '0️⃣',
    'hit': '0️⃣',
    'success': '0️⃣',
    'triumph': '0️⃣',
    'victory': '0️⃣',
    'win': '0️⃣',
    'conquest': '0️⃣',
    'achievement': '0️⃣',
    'accomplishment': '0️⃣',
    'attainment': '0️⃣',
    'fulfillment': '0️⃣',
    'realization': '0️⃣',
    'completion': '0️⃣',
    'finish': '0️⃣',
    'end': '0️⃣',
    'conclusion': '0️⃣',
    'termination': '0️⃣',
    'cessation': '0️⃣',
    'stop': '0️⃣',
    'halt': '0️⃣',
    'pause': '0️⃣',
    'break': '0️⃣',
    'rest': '0️⃣',
    'respite': '0️⃣',
    'recess': '0️⃣',
    'intermission': '0️⃣',
    'interval': '0️⃣',
    'gap': '0️⃣',
    'space': '0️⃣',
    'distance': '0️⃣',
    'remove': '0️⃣',
    'remove': '0️⃣'
  }

  // Busca por correspondências parciais
  for (const [palavraChave, icone] of Object.entries(icones)) {
    if (nomeLower.includes(palavraChave)) {
      return icone
    }
  }

  // Ícone padrão se nenhuma correspondência for encontrada
  return '📚'
}

function criarCardMateria(materia) {
  const card = document.createElement('div')
  card.className = 'card-materia'
  card.dataset.id = materia.id

  const icone = obterIconeMateria(materia.nome)
  const nomeFormatado = escaparHtmlSeguro(materia.nome)

  card.innerHTML = `
    <div class="card-materia-info">
      <span class="card-materia-icone">${icone}</span>
      <span class="card-materia-nome" title="${nomeFormatado}">${nomeFormatado}</span>
    </div>
    <button class="btn-excluir" data-id="${materia.id}" title="Excluir matéria">
      🗑️
    </button>
  `

  // Evento de excluir
  card.querySelector('.btn-excluir').addEventListener('click', () => {
    excluirMateria(materia.id, materia.nome)
  })

  return card
}

// ============================================
// ADICIONAR MATÉRIA
// ============================================
async function adicionarMateria() {
  const input = document.getElementById('input-materia')
  const btn   = document.getElementById('btn-adicionar-materia')
  const msg   = document.getElementById('msg-materia')

  const nome = input.value.trim()

  // Validação
  if (!nome) {
    mostrarMsgMateria('Digite o nome da matéria.', 'erro')
    return
  }

  if (nome.length < 2) {
    mostrarMsgMateria('O nome deve ter pelo menos 2 caracteres.', 'erro')
    return
  }

  // Desabilita botão durante o envio
  btn.disabled = true
  btn.textContent = 'Salvando...'

  const { error } = await salvarMateriaUsuario(nome)

  btn.disabled = false
  btn.textContent = '+ Adicionar'

  if (error) {
    mostrarMsgMateria('Erro ao salvar. Tente novamente.', 'erro')
    return
  }

  // Limpa o campo e recarrega a lista
  input.value = ''
  mostrarMsgMateria('Matéria adicionada com sucesso!', 'sucesso')
  carregarMaterias()

  // Limpa a mensagem após 3 segundos
  setTimeout(() => mostrarMsgMateria('', ''), 3000)
}

async function salvarMateriaUsuario(nome) {
  return db
    .from('materias')
    .insert({
      user_id: window.usuarioAtual.id,
      nome
    })
    .select('id, nome, criado_em')
    .single()
}

// ============================================
// EXCLUIR MATÉRIA
// ============================================
async function excluirMateria(id, nome) {
  const confirmar = confirm(`Deseja excluir a matéria "${nome}"?\n\nIsso não apagará questões já cadastradas.`)
  if (!confirmar) return

  const { error } = await db
    .from('materias')
    .delete()
    .eq('id', id)
    .eq('user_id', window.usuarioAtual.id)

  if (error) {
    alert('Erro ao excluir. Tente novamente.')
    return
  }

  carregarMaterias()
}

// ============================================
// MENSAGEM DE FEEDBACK
// ============================================
function mostrarMsgMateria(texto, tipo) {
  const msg = document.getElementById('msg-materia')
  msg.textContent = texto
  msg.className = `msg-materia ${tipo}`
}
